# Generated by Django 2.1.15 on 2020-09-15 17:03

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectcontact',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='connectcontact',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='connecteducation',
            name='education',
        ),
        migrations.RemoveField(
            model_name='connecteducation',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='connectexperience',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='connectexperience',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='connectlink',
            name='link',
        ),
        migrations.RemoveField(
            model_name='connectlink',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='connectskill',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='connectskill',
            name='skill',
        ),
        migrations.AddField(
            model_name='applicationsubmission',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from=['resume.title', 'job.title']),
        ),
        migrations.AlterField(
            model_name='contact',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['contact_type', 'contact']),
        ),
        migrations.AlterField(
            model_name='education',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['id', 'degree_type']),
        ),
        migrations.AlterField(
            model_name='experience',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['company.name', 'started_at']),
        ),
        migrations.AlterField(
            model_name='institution',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
        migrations.AlterField(
            model_name='link',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['link_type', 'link']),
        ),
        migrations.AlterField(
            model_name='resume',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title']),
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['id', 'description']),
        ),
        migrations.DeleteModel(
            name='ConnectContact',
        ),
        migrations.DeleteModel(
            name='ConnectEducation',
        ),
        migrations.DeleteModel(
            name='ConnectExperience',
        ),
        migrations.DeleteModel(
            name='ConnectLink',
        ),
        migrations.DeleteModel(
            name='ConnectSkill',
        ),
    ]
