# Generated by Django 2.1 on 2020-10-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree_type',
            field=models.CharField(choices=[('HSI', 'Incomplete High School'), ('HS', 'High School'), ('AS', 'Associate of Science'), ('AAS', 'Associate of Applied Science'), ('BS', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('MS', 'Masters of Science'), ('MA', 'Masters of Arts'), ('Phd', 'Doctorate')], default='BS', max_length=3),
        ),
    ]
