# Generated by Django 2.1.15 on 2020-10-28 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20201027_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
