# Generated by Django 2.1.15 on 2020-09-15 17:52

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20200915_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='location',
            field=models.CharField(default='EX/A Town', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institution',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name', 'location']),
        ),
    ]
