# Generated by Django 2.1.15 on 2020-10-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20201021_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('-ended_at', '-started_at')},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-created_at'], 'verbose_name': 'added skill'},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='version',
        ),
        migrations.AlterField(
            model_name='education',
            name='degree_type',
            field=models.CharField(choices=[('HSI', 'Incomplete High School'), ('HS', 'High School'), ('BS', 'Bachelor of Science'), ('BA', 'Bachelor of Arts'), ('MS', 'Masters of Science'), ('MA', 'Masters of Arts'), ('Phd', 'Doctorate')], default='BS', max_length=3),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
