# Generated by Django 2.1 on 2020-10-26 23:25

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='A label for company URL config', max_length=31, populate_from=['name'])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('text', models.TextField()),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=60, populate_from=['title'])),
            ],
            options={
                'verbose_name': 'published job',
                'ordering': ['-pub_date', 'title'],
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='A label for tag URL config', max_length=31, populate_from=['name'])),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organizer.Company')),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('website', models.URLField(max_length=250)),
            ],
            options={
                'ordering': ('name',),
                'get_latest_by': 'name',
            },
            bases=('organizer.company',),
        ),
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(to='organizer.Tag'),
        ),
        migrations.AddField(
            model_name='company',
            name='tags',
            field=models.ManyToManyField(to='organizer.Tag'),
        ),
        migrations.AddField(
            model_name='job',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.Partner'),
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('slug', 'partner')},
        ),
    ]
