# Generated by Django 2.1.15 on 2020-09-15 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=60)),
                ('text', models.TextField()),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.Partner')),
                ('tags', models.ManyToManyField(to='organizer.Tag')),
            ],
            options={
                'verbose_name': 'published job',
                'ordering': ['-pub_date', 'title'],
                'get_latest_by': 'pub_date',
            },
        ),
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('slug', 'partner')},
        ),
    ]
